# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml in your project root
# Replace all placeholder values with your actual credentials

[supabase]
url = "https://your-supabase-project.supabase.co"
key = "your-supabase-anon-key"

[wordpress]
url = "https://aipropiq.com"
# Remove /wp-admin or trailing slashes from URL

[woocommerce]
consumer_key = "ck_your_woocommerce_consumer_key"
consumer_secret = "cs_your_woocommerce_consumer_secret"

[rentcast]
api_key = "your-rentcast-api-key"
