# .streamlit/secrets.toml

[supabase]
url = "https://nfqqhvflehwdxyxvlgja.supabase.co/"
key = "your-supabase-key"

[wordpress]
base_url = "https://aipropiq.com/"
username = "your-username"
password = "your-password"

[general]
base_url = "https://aipropiq.com"
api_key = "your-general-api-key"
wordpress = "https://aipropiq.com"

[woocommerce]
consumer_key = "your-woocommerce-consumer-key"
consumer_secret = "your-woocommerce-consumer-secret"

[rentcast]
api_key = "your-rentcast-api-key"

